### ISSUE TITLE
Support Node 20 for building

### ISSUE THREAD

**Issue by girlbossceo** [the-draupnir-project/Draupnir#101]
Hi! It appears Draupnir does not support Node 20 for building as trying to run `yarn install` on a host with Node 20 installed errors with:

```
$ yarn install
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error matrix-appservice@1.1.0: The engine "node" is incompatible with this module. Expected version ">=14 <=18". Got "20.5.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

matrix-appservice-bridge in Draupnir's package.json, which uses matrix-appservice, is on 8.1.1 even though the latest version is 9.0.1 (https://github.com/matrix-org/matrix-appservice-bridge/releases/latest) which does add support for Node 20 and drops Node 16 support which Draupnir also recently did: https://github.com/matrix-org/matrix-appservice-bridge/commit/d5ab31242fe423ff8272e32af4e54f126afb4e86

I'm not sure how much needs to be done to make Node 20 work, but I was able to just update matrix-appservice-bridge in my package.json and it seems to work?

**Comment by MTRNord** [comment]
Hi!

I am going to have a look today. So far it seems its just a simple update. So as soon as I am at my pc I will have a look :)
