### ISSUE TITLE
Reaction handler is confusing

### ISSUE THREAD

**Issue by MTRNord** [the-draupnir-project/Draupnir#160]
See: https://matrix.to/#/!IaWNErZAgQUhGqJXjX:matrix.org/$S2YQ30oHVV-U7nlSYhHY-jQo71B9_Uj3iE7YXnPZAz4?via=matrix.org&via=envs.net&via=the-apothecary.club

Alternatives: Number emoji or alphabet instead.

**Comment by Gnuxie** [comment]
We've gone with emoji in `v2.0.0` 

![image](https://github.com/the-draupnir-project/Draupnir/assets/50846879/b9d50b8c-36ca-4af1-8d04-79f99d585eeb)
