### ISSUE TITLE
Store configuration to disk or elsewhere reliable / Matrix state resets keep altering configuration and banning benevolent users for "spam"

### ISSUE THREAD

**Issue by Mikaela** [the-draupnir-project/Draupnir#196]
I have three times disabled `basicfloodingprotection` as it keeps triggering on redactions or other expected Matrix behaviour (#187), but the change gets reverted as Matrix cannot be trusted for things such as software configuration.

Thus I think the configuration should be stored on disk or something like software usually does.

Ref: https://github.com/matrix-org/synapse/issues/8629

**Comment by Gnuxie** [comment]
This doesn't seem to be caused by state resets, since the list of enabled protections is loaded from [account data](https://github.com/the-draupnir-project/Draupnir/blob/main/src/protections/ProtectionManager.ts#L91). However this is still a Major usability issue.

**Comment by Mikaela** [comment]
And this happens again. Were there any ideas on what causes it, if not state resets?

**Comment by Gnuxie** [comment]
To be confirmed, but we suspect that under certain conditions where synapse starts and then later loses a connection to the database, it will return empty account data with a http OK response. Meaning that we have no way to detect this failure mode.

**Comment by Gnuxie** [comment]
OK turns out there was a Synapse+Redis problem specific to draupnir.midnightthoughts.space CC @MTRNord will close on confirmation.

**Comment by MTRNord** [comment]
I am monitoring this but it seems to have been resolved after the redis was fixed. Closing :)
