### ISSUE TITLE
Recieving a new policy from a watched list (e.g. a consumer of CME) doesn't cause a redaction until someone joins/leaves the room again

### ISSUE THREAD

**Issue by Gnuxie** [the-draupnir-project/Draupnir#210]
A spammer joined fluffychat's support room.
I issued a CME ban via TNO
fluffy consumed the ban and banned the user, but didn't redact the messages because nothing triggered the redaction queue
i had to force the queue to trigger by leaving and rejoining in that room. https://github.com/the-draupnir-project/Draupnir/blob/main/src/ProtectedRoomsSet.ts#L216

**Comment by Mikaela** [comment]
Easier workaround /myroomnick was just tested successfully in the Draupnir room.
