### ISSUE TITLE
[D4A] Alias Required instead of room ID for Appservice Management Room

### ISSUE THREAD

**Issue by FSG-Cat** [the-draupnir-project/Draupnir#277]
Supporting both Aliases and Room IDs would help with ease of config especially as if the user is supposed to be invited either way it doesnt actually matter if its a room ID or alias from a end user perspective and we should leave it to what they prefer. Especially as it should be a local alias alias lookup failure is not a big concern.

**Comment by Gnuxie** [comment]
Should be fixed in the latest pre-release and on develop

**Comment by Gnuxie** [comment]
yep it's fixed in the latest pre-releases
