### ISSUE TITLE
Constructed server ACLs collapsed

### ISSUE THREAD

**Issue by mahdi1234** [the-draupnir-project/Draupnir#45]
"Constructed server ACL:" message can be very long (hundreds of ACLs), it would add to readability of control room if it was collapsed by default like help command does.

**Comment by Gnuxie** [comment]
I strongly recommend going to your config and turning `verboseLogging` to `false`.

**Comment by mahdi1234** [comment]
I tried turning off verbose on one of my instances, but then I miss all those "Updating member bans in" which is sometimes useful to spot unusual joins in stale/small rooms to identify spammers. I'd still prefer to have these messages and hide ACLs. Though if you plan to remove verbose, I'll live with it :)
