### ISSUE TITLE
!draupnir protections command broken on v2.0.0-beta.6

### ISSUE THREAD

**Issue by ll-SKY-ll** [the-draupnir-project/Draupnir#555]
!draupnir protections command broken on 
commit d3fe508db3cbff900fffec5a37c6fc12c6af177f (HEAD -> main, tag: v2.0.0-beta.6, origin/main, origin/HEAD)
Author: gnuxie <Gnuxie@protonmail.com>
Date:   Wed Sep 11 18:08:23 2024 +0100

    v2.0.0-beta.6

![Screenshot_20240913_130615](https://github.com/user-attachments/assets/4e17899f-c9a8-41d9-a8bd-7d7ad95eeba9)

**Comment by Gnuxie** [comment]
yeah it seems like i forgot to intern the `protections` command into the table. The other commands that are listed in help should still work

**Comment by Gnuxie** [comment]
Thanks for reporting meow
