### ISSUE TITLE
D4A Admin room bot refuses to respond to commands.

### ISSUE THREAD

**Issue by FSG-Cat** [the-draupnir-project/Draupnir#582]
Well D4A admin bot does nothing when i tried to coax life into it. Had to manually write the allow policy to grant a new user access to my bot.

**Comment by Gnuxie** [comment]
What version?

**Comment by Gnuxie** [comment]
`v2.0.0-beta.6-27-g5ab32f9`

**Comment by FSG-Cat** [comment]
!admin works on v2.0.0-beta.6-32-g56cdc48
